### PR TITLE
Updating UI and cleaning up React components

### PR DESCRIPTION
**Pull request by CFIALeronB**
- Componentizing features.
- Adding code documentation.
- Fixing UI elements and adding a logo.

### CODE REVIEW

**Comment by rngadam** [comment]
Looks good so far. Confirm we're ready to redeploy this. 

Since this is heavily oriented towards visual changes, can you provide a screenshot of the interface or even vidcap of interaction changes in this and future pull requests summaries?

**Comment by CFIALeronB** [comment]
Screenshot 2023-06-19 152127
Screenshot 2023-06-19 152203

**Comment by rngadam** [comment]
@CFIALeronB Can you fix the query not being prefilled in the search box of the results page?

When I Google, both the query text and the search results are on screen.

**Comment by CFIALeronB** [comment]
> @CFIALeronB Can you fix the query not being prefilled in the search box of the results page?
> 
> When I Google, both the query text and the search results are on screen.

**Comment by CFIALeronB** [comment]
@rngadam Working on that now

**Comment by rngadam** [comment]
There's also a query clear button X on the right-hand side:

image

**Comment by CFIALeronB** [comment]
query term now populates the placeholder value in the search. If the user wants to search for another term it overwrites the placeholder.

**Pull request closed without merging**
